services:
  nginx:
    image: nginx
    networks:
      - pitangaweb
    volumes:
      - $CERT_BASE_PATH:/root
      - ./.docker/nginx:/etc/nginx/templates
    environment:
      API_SERVICE: https://pitanga-code:8443
      KC_URL: https://keycloak:8443
      PORT: $PORT
      SERVER_NAME: $COMMON_NAME
    ports:
      - 443:443
    depends_on:
      - keycloak
      - pitanga-code
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512mb

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pitanga-drive:/var/lib/postgresql/data
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pitangaweb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  keycloak:
    build:
      dockerfile: ./.docker/keycloak.Dockerfile
      context: .
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
      KC_DB: postgres
      KC_DB_URL: $KC_DB_URL
      KC_DB_PASSWORD: $DB_PASSWORD
      KC_DB_USERNAME: $DB_USERNAME
      # use this if you need to change the issuer uri for any reason.
      # but i recomend you to access your application and change to
      # https://localhost/auth/realms/master there.
      #
      # KEYCLOAK_FRONTEND_URL: https://keycloak:8443/auth
    networks:
      - pitangaweb
    depends_on:
      - postgres
    volumes:
      - pitanga-drive:/opt/jboss/keycloak/standalone/data/
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 800mb

  pitanga-code:
    build:
      dockerfile: ./.docker/pitanga-code.Dockerfile
      context: .
    environment:
      CHALLENGES_DB_URL: $CHALLENGES_DB_URL
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      SHOW_SQL: $SHOW_SQL
      ISSUER_URI: $ISSUER_URI
      JWK_SET_URI: $JWK_SET_URI
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroup_parent: docker.slice
    networks:
      - pitangaweb
    depends_on:
      - postgres
      - keycloak

networks:
  pitangaweb:
    driver: bridge

volumes:
  devtools:
  pitanga-drive:
