services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8005:8080
    volumes:
      - devtools:/tmp/jetty
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512mb

  nginx:
    image: nginx
    networks:
      - pitangaweb
    volumes:
      - $resource_cert_path:/root
      - ./.docker/nginx/templates:/etc/nginx/templates
    environment:
      API_SERVICE: https://localhost:8443
      KC_URL: https://keycloak:8443
    ports:
      - 443:443
    depends_on:
      - keycloak
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512mb

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pitangaweb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  keycloak:
    build:
      dockerfile: ./.docker/keycloak.Dockerfile
      context: .
      args:
        PG_URL: $KC_DB_URL
        PG_PASS: $DB_PASSWORD
        PG_NAME: $DB_USERNAME
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
    networks:
      - pitangaweb
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 800mb

networks:
  pitangaweb:
    driver: bridge

volumes:
  kafka:
  devtools:
  postgres-data:
