services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pitangaweb
    ports:
      - "5432:5432"
  keycloak:
    build:
      dockerfile: ./docker/keycloak.Dockerfile
      context: .
      args:
        HOSTNAME_URL: https://localhost:8444
        PG_URL: jdbc:postgres://postgres:5432/postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
    ports:
      - "8444:8443"
    networks:
      - pitangaweb
    depends_on:
      - postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 2G

networks:
  pitangaweb:
    driver: bridge

volumes:
  postgres-data:
