services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pitangaweb
  keycloak:
    build:
      dockerfile: ./docker/keycloak.Dockerfile
      context: .
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: changeme
    ports:
      - "8444:8443"
    networks:
      - pitangaweb
    depends_on:
      - postgres

networks:
  pitangaweb:
    driver: bridge

volumes:
  postgres-data:
