@startuml architecture
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define DEVICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICON2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2

!include <C4/C4_Container>
!include DEVICON/java.puml
!include DEVICON/react.puml
!include DEVICON2/docker.puml
!include FONTAWESOME/users.puml


' Ator utilizando o serviço
Person(aluno, "Alunos", $descr="Aluno resolvendo problemas", $sprite="users")

System_Boundary(pitanga, "Pitanga Server") {

}

Rel(aluno, web_app, "request", "https")

@enduml
