@startuml architecture
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define DEVICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICON2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2

!include <C4/C4_Container>
!include DEVICON/java.puml
!include DEVICON/react.puml
!include DEVICON/nginx.puml
!include DEVICON2/docker.puml
!include FONTAWESOME/users.puml


' Ator utilizando o serviço
Person(aluno, "Alunos", $descr="Aluno resolvendo problemas", $sprite="users")

Container(web_app, "Pitanga Web", "typescript, reactjs", "Static Web Application served through github or localhost:3000", $sprite="react")

System_Boundary(pitanga, "Pitanga Server") {
    System(nginx, "API Gateway", "API Gateway that serves KeyCloak and all subservices of Pitanga", $sprite="nginx")
    Rel(web_app, nginx, "", "https")
    Container(core, "Challenge API", "spring", "Challenges api service", $sprite="java")
    Rel_R(nginx, core, "", "http2")
}


Rel(aluno, web_app, "request", "https")

@enduml
