server:
  port: 8443
  ssl:
    certificate: classpath:certs/certificate.pem
    certificate-private-key: classpath:certs/key.pem

logging:
  level:
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  datasource:
    url: ${CHALLENGES_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    username: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://localhost/auth/realms/master}
          jwk-set-uri: ${JWK_SET_URI:https://localhost/auth/realms/master/protocol/openid-connect/certs}

pitanga:
  sandbox:
    files:
      stdin: stdin.txt
      stdout: stdout.txt
      stderr: stderr.txt
    limits:
      retry: ${MAX_EXECUTION_RETRY_ON_INTERNAL_ERROR:10}
      retry-milis: ${EXECUTION_RETRY_DELAY:100}

      cpu-time: ${CPU_TIME_LIMIT:5}
      extra-cpu-time: ${CPU_EXTRA_TIME:1}
      wall-time: ${WALL_TIME_LIMIT:10}
      memory: ${MEMORY_LIMIT:128000}
      stack: ${STACK_LIMIT:64000}

      # when creating new challenges, this will be used as max on validation
      max-cpu-time: ${MAX_CPU_TIME_LIMIT:15}
      max-extra-cpu-time: ${MAX_CPU_EXTRA_TIME:5}
      max-memory: ${MAX_MEMORY_LIMIT:512000}
      max-wall-time: ${MAX_WALL_TIME_LIMIT:20}
      max-stack: ${MAX_STACK_LIMIT:128000}
