logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
server:
  port: 8443
  ssl:
    certificate: classpath:certs/certificate.pem
    certificate-private-key: classpath:certs/key.pem
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    check-template-location: false
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8444/realms/master
          jwk-set-uri: https://localhost:8444/realms/master/protocol/openid-connect/certs
