server:
  port: 8443
  ssl:
    certificate: classpath:certs/certificate.pem
    certificate-private-key: classpath:certs/key.pem
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    username: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: ${SHOW_SQL:true}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://localhost:8444/realms/master}
          jwk-set-uri: ${JWK_SET_URI:https://localhost:8444/realms/master/protocol/openid-connect/certs}
